### ISSUE TITLE
Can't update the pod

### ISSUE THREAD

**Issue by nazz-areno** [danielgindi/ChartsRealm#10]
I am trying to update the pod with the last version `3.0.3`, but it is still downloading the `3.0.2`. Maintaining the old one I have an error in `RealmBarDataSet`. 
Xcode tells me that the "iterator" should be a var and not a constant.

**Comment by liuxuan30** [comment]
Check out swift 4 branch. We cannot push to pod right now. But the PR is ready.

**Comment by danielgindi** [comment]
@liuxuan30 @petester42 now has permissions, but I couldn't add you with your github email, CocoaPods says you are not found lol

**Comment by liuxuan30** [comment]
oh I use gmail as account.
My github public email is control by me so I can close it if I get too many trash emails
