### ISSUE TITLE
Carthage update/bootstrap download Swift 3.1 RealmSwift module for swift 4

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ChartsRealm#11]
I met a strange issue that even though I updated realm or fresh install 2.10.2, Xcode9 still complains the module is compiled with swift 3.1.

I opened one here: https://github.com/realm/realm-cocoa/issues/5384

**Comment by pmairoldi** [comment]
Ya you can't use the downloaded one you have to build from source for swift 4. I ran into the same issue.

**Comment by liuxuan30** [comment]
I updated carthage then, it will pick the right framework finally, my carthage is too old
