### ISSUE TITLE
RealmSwift dependency locked to 2.10

### ISSUE THREAD

**Issue by leenabeena** [danielgindi/ChartsRealm#16]
Hello,

We're trying to integrate this library into our app through cocoapods. Our app uses RealmSwift 3.0.2, but ChartsRealm requires 2.10.0.
Is there a reason the library is locked to an older version of realm? Is it not compatible with 3.0+?

Thanks!

**Comment by liuxuan30** [comment]
oh. I didn't update pod yet. I updated carthage. I can change to >=.

BTW RealmSwift does not have prebuilt framework for swift 4.0.3 yet, do you need swift 4.0.3? I don't know if pods can rebuild from source? carthage can do that.

**Comment by liuxuan30** [comment]
updated pod.

**Comment by liuxuan30** [comment]
sorry, I tried to push pod however multiple compile errors while carthage does not have. I think it's due to I'm building from Realm master instead of 3.0.2.

There is no solution right now, as 3.0.2 does not work with latest ChartsRealm. You have to wait Realm release a new one. Or use Carthage.

**Comment by marchv** [comment]
Hi :)

Could this one be reopened please? It is not possible to use Realm 3.1.0 and ChartsRealm using Cocoapods :S

Thanks a lot in advance :)

**Comment by liuxuan30** [comment]
pod have to wait as no prebuilt binary works. I don't know why. You could file a PR to make it work and I can merge it.
When RealmSwift released a 4.0.3 compatible version, we will update pod.
