### ISSUE TITLE
Correct way to persist data with ChartDataEntry

### ISSUE THREAD

**Issue by renjithn** [danielgindi/ChartsRealm#2]
Thanks for the great library. This is not an issue but some help would be appreciated. The Realm helper classes  for eg. RealmBarDataSet now seems only map the xValueFields and yValueFields of the element into ChartDataEntry. How can one map some custom data to the useful properties like .data of ChartDataEntry class?

**Comment by pmairoldi** [comment]
You can checkout `RealmBubbleDataSet` which exposes an extra field for the bubble size. You could apply the same idea to what you want to do.
