### ISSUE TITLE
Swift 4.1 Xcode 9.3?

### ISSUE THREAD

**Issue by theMoe** [danielgindi/ChartsRealm#21]
Hi,

I get this error:

"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."

Coud you please update to Swift 4.1?

Best regards,

Moe

**Comment by liuxuan30** [comment]
This repo is not released as prebuilt framework. You just grab the source code and compile, if no mandatory swift syntax migration required.
