### ISSUE TITLE
Throwing errors on XCode 10 / iOS12

### ISSUE THREAD

**Issue by patreu22** [danielgindi/ChartsRealm#23]
Hey there,
ChartsRealm throws a lot of compiling errors since the update, is there by chance a date we can expect an update for the pod?

**Comment by liuxuan30** [comment]
not really sure how much of the work. Can you try to make a PR for us?
I could take a look maybe next week.

I recall one of the major problem is about Realm itself. In last update cycle, Realm take a long time to release a Swift 4.0 framework. Not checked this year yet. If Realm released Swift 4.2 binary, it should be very easy to update ChartsRealm.

**Comment by frasza** [comment]
It would be amazing to get the update for 4.2. Just integrating the Charts with Realm and errors are giving me much problems.

**Comment by liuxuan30** [comment]
After fixing Charts issues, maybe I can take a look early next week

**Comment by frasza** [comment]
Thank would be amazing, thank you for your effort @liuxuan30

**Comment by kierobinson1** [comment]
Hi,
Is there any update to this? I've just updated to the latest Swift 4.2 version & having the compiling errors

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/ChartsRealm/pull/24
it should be fixed
