### ISSUE TITLE
Xcode 10.1 / Swift 4.2

### ISSUE THREAD

**Issue by vikas100** [danielgindi/ChartsRealm#29]

**Comment by vikas100** [comment]
![Screenshot 2019-04-24 at 4 44 25 PM](https://user-images.githubusercontent.com/5698926/56655387-40dccc00-66b0-11e9-9198-24bf2d54d1ee.png)


This library does not support to xcode 10.1 & swift 4.2  in RealmBaseDataSet Class

Can you fix it

**Comment by liuxuan30** [comment]
can you help fix it with Swift 5 and Xcode 10.2.1?
I have a tight project, so I don't think I can take a look before next two weeks
