### ISSUE TITLE
ChartsRealm 3.0.2 Error in Xcode 9 beta: Use of mutating member on immutable value

### ISSUE THREAD

**Issue by ianrahman** [danielgindi/ChartsRealm#3]
`RealmBarDataSet` line 204
![screen shot 2017-08-18 at 3 37 26 pm](https://user-images.githubusercontent.com/16245367/29474809-3bec59fe-842b-11e7-87af-223c989670f7.png)

`RealmBaseDataSet` line 242
![screen shot 2017-08-18 at 3 40 24 pm](https://user-images.githubusercontent.com/16245367/29474892-94880cc0-842b-11e7-9b1e-cc2519b6db37.png)

ChartsRealm produces the above errors in Xcode 9 beta. Should be a quick fix.

**Comment by liuxuan30** [comment]
We shall hold after Xcode 9 released, thank you!

**Comment by thefredelement** [comment]
Any update?

**Comment by regularRichi** [comment]
hi, any update? +1

**Comment by liuxuan30** [comment]
welcome to create swift 4 change for ChartsRealm and we are happy to merge. We will do it anyway but need some days. Too many things on my plate.

**Comment by liuxuan30** [comment]
As Realm does not release Swift 4, we would hold for a while; letting Xcode 9 to do conversion requires a successful build.

**Comment by marbetschar** [comment]
@gazz94 😍
@liuxuan can we get this merged somehow? This issue prevents me from working further :(

**Comment by liuxuan30** [comment]
swift 4 realm has not released yet, and Xcode9 won't allow conversion if we cannot make a successful build.
You are welcome to file a PR. But honestly, if realm does not release swift 4 version, you can't go further neither. I do went to Realm github, but I don't see a branch that is for swift 4, nor a release. Searching the issues just get me "it's ongoing".

Personal suggestion is using swift 3.2 until all things settle down.

**Comment by marbetschar** [comment]
@liuxuan30 I see. Is it possible to somehow ignore ChartsRealm? Since I don't use it anyway (don't use Realm neither) - but for some reason it comes with Charts automatically when using Carthage.

**Comment by liuxuan30** [comment]
I think you made a mistake. Charts are now a separate project. This repo means to be realm related only. If you don't need realm, you shouldn't look at this repo at all.. 
And Charts itself is already Swift 4!

**Comment by marbetschar** [comment]
@liuxuan30 hoping you can help out then? Because the only thing I have in my `Cartfile` is `github "Mandelkind/Charts" "feature-attributedentry"` - since I rely on features I added in the past (a pull request for `Charts` is hanging).

For some reason `ChartsRealm` is also compiled (at least `carthage` tries to do so) when I run `carthage update --platform iOS`.

How to get out of this hell? :(

FWIW here's the full output - don't know why it's building Realm, since this is not in my Cartfile. Maybe due to the same reason it builds ChartsRealm?

```
$ carthage update --platform iOS
...
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "Charts" in Charts.xcodeproj
*** Building scheme "ChartsRealm" in Charts.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/marbetschar/Development/Valletti/iOS/Carthage/Checkouts/Charts/Charts.xcodeproj -scheme ChartsRealm -configuration Release -derivedDataPath /Users/marbetschar/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Charts/0fdf07ca60643e558622a55e0e247a0ee37b23eb -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/marbetschar/Development/Valletti/iOS/Carthage/Checkouts/Charts)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/ns/0h9r9v5908x4x67v5j9wvhvw0000gn/T/carthage-xcodebuild.X96z13.log
```

**Comment by pmairoldi** [comment]
If you are not keeping your fork up to date with our changes then we can't really help you. Basically delete the ChartsRealm targets from the xcode project in your fork and try it again.

**Comment by marbetschar** [comment]
@petester42 thanks für pointing out I‘ve missed that. Despite its kind of obvious - did not thought about that 😜

FWIW: basically it’s not a fork, still waiting for the pull request to get merged. And the pull request is there in order to avoid issues exactly like this. That said it would be cool to get to a decision for the PR. I don’t care if the decision is to merge it or delete it - but laying around in an undefined state is „a bit unlucky“.

**Comment by dasoga** [comment]
Hey guys!

Realm just updated to 2.10.2 supporting Swift 4...I hope you can update soon. Thank you in advance.

**Comment by pmairoldi** [comment]
@marbetschar I have no idea what pull request you're talking about.

**Comment by pmairoldi** [comment]
@dasoga i'm working on it today. 3.0.3 should be out soon with swift 3.2 support and 3.0.4 later today with swift 4 support.

**Comment by dasoga** [comment]
Thank you for your time @petester42

**Comment by pmairoldi** [comment]
3.0.3 and 3.0.4 are out now. enjoy
