### ISSUE TITLE
Would you update to Swift 5.0 ? Or have a schedule?

### ISSUE THREAD

**Issue by CaffeCat** [danielgindi/ChartsRealm#30]

**Comment by pimoon** [comment]
Anyone get this thing working with latest realm and swift 5 ?

I can't build because there is errors in code :  

```
1/ Pods/ChartsRealm/ChartsRealm/Classes/Data/RealmBaseDataSet.swift:628:24: Method does not override any method from its superclass

2/ Pods/ChartsRealm/ChartsRealm/Classes/Data/RealmBaseDataSet.swift:630:20: Static member 'copyWithZone' cannot be used on instance of type 'ChartBaseDataSet'

3/ Pods/ChartsRealm/ChartsRealm/Classes/Data/RealmPieDataSet.swift:19:12: Type 'RealmPieDataSet' does not conform to protocol 'IPieChartDataSet'

```

**Comment by liuxuan30** [comment]
sorry. been really busy recently. I don't expect I can do it this month. or at least before the end of May.

There is an PR used to be supporting new swift versions, but not the latest. I pinned the author but no luck yet.
You are welcome to file a PR as well, I'm happy to review and merge it.
