### ISSUE TITLE
How to use this with Swift Realm ? Can't init DataSet

### ISSUE THREAD

**Issue by wojczitsu** [danielgindi/ChartsRealm#32]
I've got:

```
class Statistics: Object {
...
}

func dataForChart() -> Results<Statistics>? {
        var result: Results<Statistics>?
        do {
            let realm = try Realm()
            result = realm.objects(Statistics.self)
        } catch let error as NSError {
            print("Realm error - get all: \(error.localizedDescription)")
        }
        return result
}

let set = RealmLineDataSet(results: database.dataForChart(), xValueField: "date", yValueField: yField) // this won't compile 
```

Last line gives error: Cannot invoke initializer for type 'RealmLineDataSet' with an argument list of type '(results: Results<Statistics>?, xValueField: String, yValueField: String?)'

**Comment by liuxuan30** [comment]
seems you are using different version of Realm. Please check README for the version we supported.
to be honest I think this library is not ready to use for generic cases. refer https://github.com/danielgindi/ChartsRealm/pull/17
