### ISSUE TITLE
Crash on iOS13 ! need to update RealmSwift

### ISSUE THREAD

**Issue by MattOzOz** [danielgindi/ChartsRealm#33]
Hello,
It seems you have to update dependency : s.dependency "RealmSwift", "~> 3.18.0" // Instead 3.15.0
I'm not enough skill to make a pull request :/

**Comment by liuxuan30** [comment]
eh.. maybe the best time to learn? :) 

Otherwise I will take a look this week.

**Comment by jakemor** [comment]
Any updates?

**Comment by jakemor** [comment]
@liuxuan30 how much work needs to be done to alter the dependency for Realm from 3.15 to 3.18? It doesn't seem like they announced any breaking changes https://github.com/realm/realm-cocoa/releases. How can I do this myself?

**Comment by liuxuan30** [comment]
I'm working on it. Release soon, if all we need is bump version number
