### ISSUE TITLE
Is this possible to use with project catalyst?

### ISSUE THREAD

**Issue by gheorghecr** [danielgindi/ChartsRealm#35]
I am trying to run my app on my Mac, but I get this error :

/Pods/Realm/core/librealmcore-ios.a(bptree.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64

I am wondering if this has something to do with this framework

**Comment by liuxuan30** [comment]
as your error message said, you have to choose a x64 version of Realm. 

Better you go to Realm repo ask for this, or build yourself.
